package LCTRSTree.Visitors;

import parser.*;
import LCTRSTree.*;

/**
 * Visitor class for an expression within the ANTLR parse tree created that allows for the creation and return of an
 * expression, depending on the contents at the current child in the ANTRL tree.
 * Given that an expression can itself be a combination of expressions, this class will recursively call down
 * into each child until a base case expression is returned, which will either be a constant or an integer.
 * Given a constant or a variable it will simply return the value at that point in the parse tree.
 *
 * @author Andrew Harrison
 */

public class ExpressionVisitor extends LctrsParserBaseVisitor<Expression> {


    /**
     * Visitor for an expression, which is found in the body of the Python Parse tree generated by ANTLR. It will either
     * visit an expr node or a test node depending on which passed in and will then return an expression created based
     * on the items in the expr given. It will check first if the INTEGER or IDENTIFIER tokens are empty, and if they are not
     * it knows that we do not have a compound expression and so will return a new object of the type that we have. Otherwise
     * it knows that we have an operation and therefore must return some compound expression.
     *
     * @param ctx the parse tree is the expression context object produced by ANTLR that is passed into the
     *            visit expression
     * @return an expression based on the content of the ExprContext passed in as an argument
     *
     */

    @Override
    public Expression visitExpr(LctrsParser.ExprContext ctx){
        if (ctx.INTEGER() != null) {
            return new Constant(ctx.INTEGER().getText());
        }

        if (ctx.IDENTIFIER() != null) {
            return new Variable(ctx.IDENTIFIER().getText());
        }

        Expression left = visit(ctx.expr(0));
        Expression right = visit(ctx.expr(1));

        return new Operation(left, ctx.operation.getText(), right);
    }

    /**
     * A visitor method for a test, which is defined by the use of a comparison operator within some expression.
     * A test is definied seperately within the parser file used for ANTLR and therefore we use a different visitor method
     * to access it. However, this is still and operation and therefore we can still class it as such when building our
     * LCTRS tree.
     *
     * @param ctx the parse tree
     * @return an Expression built using the left and right hand side of a comparison operator, with the operation being
     * found within the comparator token.
     */
    @Override
    public Expression visitTest(LctrsParser.TestContext ctx){
        Expression left = visit(ctx.expr(0));
        Expression right = visit(ctx.expr(1));
        return new Operation(left, ctx.comparator().getText(), right);
    }
}
